import flet as fl

dashboard = fl.Column(
    [
        fl.Row(
            [
                fl.Card(
                    elevation=20,
                    content=fl.Container(
                        padding=20,
                        height=120,
                        width=270,
                        border_radius=fl.border_radius.only(
                            top_right=30,
                            bottom_left=30,
                        ),
                        content=fl.Column(
                            [
                                fl.Row(
                                    [
                                        fl.Text(
                                            "1.31 GB",
                                            weight="bold",
                                            size=30,
                                        ),
                                    ],
                                    alignment="center",
                                ),
                                fl.Row(
                                    [
                                        fl.Text(
                                            "Cleanup Suggested",
                                            color="#87888A",
                                            size=10,
                                        ),
                                    ],
                                    alignment="center",
                                ),
                            ],
                            alignment="center",
                        ),
                    ),
                ),
            ],
            alignment="center",
        ),
        fl.Row(
            [
                fl.ProgressBar(
                    width=300,
                    value=0.4,
                )
            ],
            alignment="center",
        ),
        fl.Row(
            [
                fl.Container(
                    content=fl.Row(
                        [
                            fl.Icon(
                                fl.icons.THUMB_UP,
                                size=20,
                                color="black",
                            ),
                            fl.Text(
                                "Used 3.2 GB",
                                size=15,
                                color="black",
                                weight="bold",
                            ),
                        ],
                        alignment="center",
                    )
                ),
                fl.Container(
                    content=fl.Row(
                        [
                            fl.Icon(
                                fl.icons.EMOJI_OBJECTS,
                                size=20,
                                color="black",
                            ),
                            fl.Text(
                                "Deleted 3.1 GB",
                                size=15,
                                color="black",
                                weight="bold",
                            ),
                        ],
                        alignment="center",
                    )
                ),
            ],
            alignment="center",
        ),
    ]
)
