import flet as fl

bottom_bar = fl.Container(
    margin=30,
    # border_radius=10,
    content=fl.Card(
        elevation=30,
        content=fl.Container(
            bgcolor="white",
            content=fl.Row(
                [
                    fl.Container(
                        padding=10,
                        content=fl.Column(
                            [
                                fl.CircleAvatar(
                                    content=fl.Icon(
                                        fl.icons.MOTORCYCLE,
                                        size=30,
                                        color="white",
                                    ),
                                    bgcolor="#00A911",
                                ),
                                fl.Text(
                                    "GoRide",
                                    weight="bold",
                                    color="grey",
                                    size=20,
                                ),
                            ],
                            alignment="center",
                            horizontal_alignment="center",
                        ),
                    ),
                    fl.Container(
                        padding=10,
                        content=fl.Column(
                            [
                                fl.CircleAvatar(
                                    content=fl.Icon(
                                        fl.icons.DEPARTURE_BOARD,
                                        size=30,
                                        color="white",
                                    ),
                                    bgcolor="#00A911",
                                ),
                                fl.Text(
                                    "GoShop",
                                    weight="bold",
                                    color="grey",
                                    size=20,
                                ),
                            ],
                            alignment="center",
                            horizontal_alignment="center",
                        ),
                    ),
                    fl.Container(
                        padding=10,
                        content=fl.Column(
                            [
                                fl.CircleAvatar(
                                    content=fl.Icon(
                                        fl.icons.DEPARTURE_BOARD,
                                        size=30,
                                        color="white",
                                    ),
                                    bgcolor="lightblue",
                                ),
                                fl.Text(
                                    "GoCar",
                                    weight="bold",
                                    color="grey",
                                    size=20,
                                ),
                            ],
                            alignment="center",
                            horizontal_alignment="center",
                        ),
                    ),
                    fl.Container(
                        padding=10,
                        content=fl.Column(
                            [
                                fl.CircleAvatar(
                                    content=fl.Icon(
                                        fl.icons.RESTAURANT,
                                        size=30,
                                        color="white",
                                    ),
                                    bgcolor="orange",
                                ),
                                fl.Text(
                                    "GoCar",
                                    weight="bold",
                                    color="grey",
                                    size=20,
                                ),
                            ],
                            alignment="center",
                            horizontal_alignment="center",
                        ),
                    ),
                ],
                alignment="spaceAround",
            ),
        ),
    ),
)
